import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; 
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Checklist app",
  description: "Generated by ibrsec",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>

      <body className={inter.className}> 
          <Navbar />
          {children} 
      </body>
      </StoreProvider>
    </html>
  );
}
